nelmio_api_doc:
    documentation:
        info:
            title: Colllect
            description: 'Your visual bookmark manager'
            version: 1.0.0
        securityDefinitions:
            OAuth2Password:
                type: oauth2
                flow: password
                tokenUrl: '/api/oauth/token'
                scopes:
                    superadmin: 'Grants all access'
        security:
            - OAuth2Password: []
        definitions:
            Token:
                type: object
                properties:
                    token_type:
                        type: string
                    expires_in:
                        type: integer
                    access_token:
                        type: string
                        description: 'JWT'
                    refresh_token:
                        type: string
        produces:
            - application/json

    models:
        names:
            - alias: Element
              type: App\Model\Element\AbstractElement
            - alias: User
              type: App\Entity\User
              groups: ['public']
            - alias: CurrentUser
              type: App\Entity\User
              groups: ['public', 'current']

    areas:
        default: # Public
            with_annotation: true
        admin:
            path_patterns:
              - ^/api(?!/doc(/.*)?(.json)?$) # Accepts routes under /api except /api/doc
