trikoder_oauth2:
    authorization_server:
        # Full path to the private key file.
        # How to generate a private key: https://oauth2.thephpleague.com/installation/#generating-public-and-private-keys
        private_key: '%env(resolve:OAUTH2_PRIVATE_KEY_PATH)%'

        # The string used as an encryption key.
        # How to generate an encryption key: https://oauth2.thephpleague.com/installation/#string-password
        encryption_key: '%env(string:OAUTH2_ENCRYPTION_KEY)%'

    resource_server:
        # Full path to the public key file
        # How to generate a public key: https://oauth2.thephpleague.com/installation/#generating-public-and-private-keys
        public_key: '%env(resolve:OAUTH2_PUBLIC_KEY_PATH)%'

    # Scopes that you wish to utilize in your application.
    # This should be a simple array of strings.
    scopes: ['superadmin']

    # Configures different persistence methods that can be used by the bundle for saving client and token data.
    # Only one persistence method can be configured at a time.
    persistence:
        doctrine:
            # Name of the entity manager that you wish to use for managing clients and tokens.
            entity_manager: default
