app.security:
    resource: '../../src/Controller/SecurityController.php'
    type: annotation
    name_prefix: 'app_security_'

app.proxy:
    resource: '../../src/Controller/ProxyController.php'
    type: annotation
    name_prefix: 'app_proxy_'

api.oauth:
    resource: '../../src/Controller/Api/OAuthServerController.php'
    type: annotation
    prefix: /api/oauth
    name_prefix: 'api_oauth_'
    trailing_slash_on_root: false
    defaults:
        _format: json

api.users:
    resource: '../../src/Controller/Api/UserController.php'
    type: annotation
    prefix: /api/users
    name_prefix: 'api_users_'
    trailing_slash_on_root: false
    defaults:
        _format: json

api.colllections:
    resource: '../../src/Controller/Api/ColllectionController.php'
    type: annotation
    prefix: /api/colllections
    name_prefix: 'api_colllections_'
    trailing_slash_on_root: false
    defaults:
        _format: json

api.colllection_elements:
    resource: '../../src/Controller/Api/ColllectionElementController.php'
    type: annotation
    prefix: /api/colllections/{encodedColllectionPath}/elements
    name_prefix: 'api_colllection_elements'
    trailing_slash_on_root: false
    defaults:
        _format: json

api.colllection_tags:
    resource: '../../src/Controller/Api/ColllectionTagController.php'
    type: annotation
    prefix: /api/colllections/{encodedColllectionPath}/tags
    name_prefix: 'api_colllection_tags'
    trailing_slash_on_root: false
    defaults:
        _format: json
