app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

api.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc

api.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

api.tokens:
    type: rest
    resource: ApiBundle\Controller\TokenController
    prefix: /api

api.users:
    type: rest
    resource: ApiBundle\Controller\UserController
    prefix: /api

api.colllections:
    type: rest
    resource: ApiBundle\Controller\ColllectionController
    prefix: /api

api.colllection_elements:
    type: rest
    resource: ApiBundle\Controller\ColllectionElementController
    prefix: /api

api.colllection_tags:
    type: rest
    resource: ApiBundle\Controller\ColllectionTagController
    prefix: /api
