app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc

tokens:
    type: rest
    resource: ApiBundle\Controller\TokenController
    prefix: /api

users:
    type: rest
    resource: ApiBundle\Controller\UserController
    prefix: /api

collections:
    type: rest
    resource: ApiBundle\Controller\CollectionController
    prefix: /api

collection_elements:
    type: rest
    resource: ApiBundle\Controller\CollectionElementController
    prefix: /api

collection_tags:
    type: rest
    resource: ApiBundle\Controller\CollectionTagController
    prefix: /api
