# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    api.security.jwt_authenticator:
        class: ApiBundle\Security\JwtAuthenticator
        autowire: true

    app.security.jwt_authenticator:
        class: AppBundle\Security\JwtAuthenticator
        autowire: true

    api.doctrine.hash_password_listener:
        class: ApiBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    api.api_doc.fos_rest_form_errors_parser:
        class: ApiBundle\Parser\FOSRestFormErrorsParser
        tags:
            - { name: nelmio_api_doc.extractor.parser, priority: 1 }

    api.filesystem_adapter_manager:
        class: ApiBundle\FilesystemAdapter\FilesystemAdapterManager
        arguments: ["%default_adapter%"]

    api.flysystem.local:
        class: ApiBundle\FilesystemAdapter\Local
        public: false
        arguments: ["%local_root_path%"]
        tags:
            - { name: api.filesystem_adapter, alias: local }

    api.flysystem.aws_s3:
        class: ApiBundle\FilesystemAdapter\AwsS3
        public: false
        arguments: ["%aws_s3_key%", "%aws_s3_secret%", "%aws_s3_region%", "%aws_s3_bucket%"]
        tags:
            - { name: api.filesystem_adapter, alias: aws_s3 }

    api.flysystem.dropbox:
        class: ApiBundle\FilesystemAdapter\Dropbox
        public: false
        tags:
            - { name: api.filesystem_adapter, alias: dropbox }

    api.flysystem.ftp:
        class: ApiBundle\FilesystemAdapter\Ftp
        public: false
        arguments: ["%ftp_host%", "%ftp_port%", "%ftp_username%", "%ftp_password%", "%ftp_root%"]
        tags:
            - { name: api.filesystem_adapter, alias: ftp }

    api.flysystem.sftp:
        class: ApiBundle\FilesystemAdapter\Sftp
        public: false
        arguments: ["%sftp_host%", "%sftp_port%", "%sftp_username%", "%sftp_password%", "%sftp_root%"]
        tags:
            - { name: api.filesystem_adapter, alias: sftp }

    api.service.collection:
        class: ApiBundle\Service\CollectionService
        autowire: true

    api.service.collection_element:
        class: ApiBundle\Service\CollectionElementService
        autowire: true

    api.service.collection_tag:
        class: ApiBundle\Service\CollectionTagService
        autowire: true

    api.service.element_file_handler:
        class: ApiBundle\Service\ElementFileHandler
